# This is a basic workflow to help you get started with Actions

name: sshdemo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
    - run: |
        cat ~/.ssh/id_rsa
        ssh -vvv -o "StrictHostKeyChecking no" runner@localhost
 #ssh -vvv localhost -p 22

 #>> /root/.ssh/authorized_keys 

  #ssh -o StrictHostKeyChecking=no root@localhost

